export const events = [
  {
    id: 1,
    title: "React Summit 2026",
    image: "/images/event1.png",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "June 2-3, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    id: 2,
    title: "DevFest Global 2026",
    image: "/images/event2.png",
    slug: "devfest-global-2026",
    location: "Multiple Cities",
    date: "November 15-17, 2026",
    time: "10:00 AM - 5:00 PM",
  },
  {
    id: 3,
    title: "Node.js Interactive",
    image: "/images/event3.png",
    slug: "nodejs-interactive",
    location: "Austin, Texas, USA",
    date: "April 20-22, 2026",
    time: "9:00 AM - 7:00 PM",
  },
  {
    id: 4,
    title: "AWS re:Invent",
    image: "/images/event4.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, Nevada, USA",
    date: "November 28 - December 2, 2026",
    time: "8:00 AM - 8:00 PM",
  },
  {
    id: 5,
    title: "Google I/O",
    image: "/images/event5.png",
    slug: "google-io-2026",
    location: "Mountain View, California, USA",
    date: "May 18-20, 2026",
    time: "10:00 AM - 6:00 PM",
  },
  {
    id: 6,
    title: "Web Summit",
    image: "/images/event6.png",
    slug: "web-summit-2026",
    location: "Lisbon, Portugal",
    date: "October 25-27, 2026",
    time: "9:00 AM - 9:00 PM",
  },
];
